title: Junya TAKAYAMA
url: "https://junya-takayama.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "#aboutme"
 - name: "Research"
   link: "#research"
 - name: "Publications"
   link: "#publications"
 - name: "Skills"
   link: "#skills"
 - name: "History"
   link: "#history"
