title: Junya TAKAYAMA
url: "https://junya-takayama.github.io"
baseurl: ""

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/"
# - name: "Contact"
#   link: "contact"
