title: Junya TAKAYAMA
url: "https://junya-takayama.github.io"
baseurl: ""

markdown: kramdown

google_analytics: UA-128655489-1
tracking_id: UA-128655489-1

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "#aboutme"
 - name: "Research"
   link: "#research"
 - name: "Awards"
   link: "#awards"
 - name: "Publications"
   link: "#publications"
 - name: "Skills"
   link: "#skills"
 - name: "Education"
   link: "#education"
   
